baseurl = "/"
languageCode = "pt-br"
languageLang = "pt"
title = "Estúdiooca"
googleAnalytics = "UA-165213725-1"
[params]
description = "Mentoria em gestão ágil. Aprenda a gerenciar produtos digitais com metodologias ágeis.Mentoria em UX design e em gerenciamento de produto (Product Management) para grupos e/ou indivíduos que precisam melhorar suas habilidades.Aprenda a escalar um time ágil e a identificar e desenvolver talentos para trabalhar com o seu produto"
images = ["/img/og-image.jpg"]
title = "Estúdiooca"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
#disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[taxonomies]
  author = "authors"
  tag = "tags"








