baseurl = "/"
languageCode = "pt-br"
languageLang = "pt"
title = "Homepage"
googleAnalytics = "UA-149460038-1"

[params]
  description = "Organize times e desenvolva habilidades técnicas essências - Bom para startups e empresas que precisam melhorar as habilidades técnicas individuais ou de equipes de produto com foco em Ágil e Scrum. Bom para pessoas interessadas em aprender ou treinar suas habilidades como product manager, product owner e UX designers em Ágil e Scrum."
  images = ["/img/og-image.jpg"]
  title = "Estúdiooca"

[params]
description = "Text about this post"
images = ["post-cover.png"]
title = "Post title"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]



